//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EC.DataAccess.PromotionService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SiteString", Namespace="http://schemas.datacontract.org/2004/07/System.Security.Util")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EC.DataAccess.PromotionService.DirectoryString))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EC.DataAccess.PromotionService.LocalSiteString))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EC.DataAccess.PromotionService.URLString))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(object[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EC.Entities.Entities.Promotion))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Security.Policy.Url))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Security.Policy.EvidenceBase))]
    public partial class SiteString : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private object[] m_separatedSiteField;
        
        private string m_siteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public object[] m_separatedSite {
            get {
                return this.m_separatedSiteField;
            }
            set {
                if ((object.ReferenceEquals(this.m_separatedSiteField, value) != true)) {
                    this.m_separatedSiteField = value;
                    this.RaisePropertyChanged("m_separatedSite");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string m_site {
            get {
                return this.m_siteField;
            }
            set {
                if ((object.ReferenceEquals(this.m_siteField, value) != true)) {
                    this.m_siteField = value;
                    this.RaisePropertyChanged("m_site");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DirectoryString", Namespace="http://schemas.datacontract.org/2004/07/System.Security.Util")]
    [System.SerializableAttribute()]
    public partial class DirectoryString : EC.DataAccess.PromotionService.SiteString {
        
        private bool m_checkForIllegalCharsField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool m_checkForIllegalChars {
            get {
                return this.m_checkForIllegalCharsField;
            }
            set {
                if ((this.m_checkForIllegalCharsField.Equals(value) != true)) {
                    this.m_checkForIllegalCharsField = value;
                    this.RaisePropertyChanged("m_checkForIllegalChars");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LocalSiteString", Namespace="http://schemas.datacontract.org/2004/07/System.Security.Util")]
    [System.SerializableAttribute()]
    public partial class LocalSiteString : EC.DataAccess.PromotionService.SiteString {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="URLString", Namespace="http://schemas.datacontract.org/2004/07/System.Security.Util")]
    [System.SerializableAttribute()]
    public partial class URLString : EC.DataAccess.PromotionService.SiteString {
        
        private EC.DataAccess.PromotionService.DirectoryString m_directoryField;
        
        private string m_fullurlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool m_isUncShareField;
        
        private EC.DataAccess.PromotionService.LocalSiteString m_localSiteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool m_parseDeferredField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool m_parsedOriginalField;
        
        private int m_portField;
        
        private string m_protocolField;
        
        private EC.DataAccess.PromotionService.SiteString m_siteStringField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string m_urlOriginalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string m_userpassField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public EC.DataAccess.PromotionService.DirectoryString m_directory {
            get {
                return this.m_directoryField;
            }
            set {
                if ((object.ReferenceEquals(this.m_directoryField, value) != true)) {
                    this.m_directoryField = value;
                    this.RaisePropertyChanged("m_directory");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string m_fullurl {
            get {
                return this.m_fullurlField;
            }
            set {
                if ((object.ReferenceEquals(this.m_fullurlField, value) != true)) {
                    this.m_fullurlField = value;
                    this.RaisePropertyChanged("m_fullurl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool m_isUncShare {
            get {
                return this.m_isUncShareField;
            }
            set {
                if ((this.m_isUncShareField.Equals(value) != true)) {
                    this.m_isUncShareField = value;
                    this.RaisePropertyChanged("m_isUncShare");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public EC.DataAccess.PromotionService.LocalSiteString m_localSite {
            get {
                return this.m_localSiteField;
            }
            set {
                if ((object.ReferenceEquals(this.m_localSiteField, value) != true)) {
                    this.m_localSiteField = value;
                    this.RaisePropertyChanged("m_localSite");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool m_parseDeferred {
            get {
                return this.m_parseDeferredField;
            }
            set {
                if ((this.m_parseDeferredField.Equals(value) != true)) {
                    this.m_parseDeferredField = value;
                    this.RaisePropertyChanged("m_parseDeferred");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool m_parsedOriginal {
            get {
                return this.m_parsedOriginalField;
            }
            set {
                if ((this.m_parsedOriginalField.Equals(value) != true)) {
                    this.m_parsedOriginalField = value;
                    this.RaisePropertyChanged("m_parsedOriginal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int m_port {
            get {
                return this.m_portField;
            }
            set {
                if ((this.m_portField.Equals(value) != true)) {
                    this.m_portField = value;
                    this.RaisePropertyChanged("m_port");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string m_protocol {
            get {
                return this.m_protocolField;
            }
            set {
                if ((object.ReferenceEquals(this.m_protocolField, value) != true)) {
                    this.m_protocolField = value;
                    this.RaisePropertyChanged("m_protocol");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public EC.DataAccess.PromotionService.SiteString m_siteString {
            get {
                return this.m_siteStringField;
            }
            set {
                if ((object.ReferenceEquals(this.m_siteStringField, value) != true)) {
                    this.m_siteStringField = value;
                    this.RaisePropertyChanged("m_siteString");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string m_urlOriginal {
            get {
                return this.m_urlOriginalField;
            }
            set {
                if ((object.ReferenceEquals(this.m_urlOriginalField, value) != true)) {
                    this.m_urlOriginalField = value;
                    this.RaisePropertyChanged("m_urlOriginal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string m_userpass {
            get {
                return this.m_userpassField;
            }
            set {
                if ((object.ReferenceEquals(this.m_userpassField, value) != true)) {
                    this.m_userpassField = value;
                    this.RaisePropertyChanged("m_userpass");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PromotionService.IPromotionService")]
    public interface IPromotionService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPromotionService/TestConnection", ReplyAction="http://tempuri.org/IPromotionService/TestConnectionResponse")]
        string TestConnection();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPromotionService/TestConnection", ReplyAction="http://tempuri.org/IPromotionService/TestConnectionResponse")]
        System.Threading.Tasks.Task<string> TestConnectionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPromotionService/CreatePromotion", ReplyAction="http://tempuri.org/IPromotionService/CreatePromotionResponse")]
        void CreatePromotion(EC.Entities.Entities.Promotion item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPromotionService/CreatePromotion", ReplyAction="http://tempuri.org/IPromotionService/CreatePromotionResponse")]
        System.Threading.Tasks.Task CreatePromotionAsync(EC.Entities.Entities.Promotion item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPromotionService/GetByIdPromotion", ReplyAction="http://tempuri.org/IPromotionService/GetByIdPromotionResponse")]
        EC.Entities.Entities.Promotion GetByIdPromotion(System.Nullable<int> id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPromotionService/GetByIdPromotion", ReplyAction="http://tempuri.org/IPromotionService/GetByIdPromotionResponse")]
        System.Threading.Tasks.Task<EC.Entities.Entities.Promotion> GetByIdPromotionAsync(System.Nullable<int> id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPromotionService/GetAllPromotions", ReplyAction="http://tempuri.org/IPromotionService/GetAllPromotionsResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EC.DataAccess.PromotionService.URLString))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EC.DataAccess.PromotionService.SiteString))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EC.DataAccess.PromotionService.DirectoryString))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EC.DataAccess.PromotionService.LocalSiteString))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EC.Entities.Entities.Promotion))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Security.Policy.Url))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Security.Policy.EvidenceBase))]
        object GetAllPromotions();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPromotionService/GetAllPromotions", ReplyAction="http://tempuri.org/IPromotionService/GetAllPromotionsResponse")]
        System.Threading.Tasks.Task<object> GetAllPromotionsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPromotionService/DeletePromotion", ReplyAction="http://tempuri.org/IPromotionService/DeletePromotionResponse")]
        void DeletePromotion(System.Nullable<int> id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPromotionService/DeletePromotion", ReplyAction="http://tempuri.org/IPromotionService/DeletePromotionResponse")]
        System.Threading.Tasks.Task DeletePromotionAsync(System.Nullable<int> id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPromotionService/UpdatePromotion", ReplyAction="http://tempuri.org/IPromotionService/UpdatePromotionResponse")]
        void UpdatePromotion(System.Nullable<int> id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPromotionService/UpdatePromotion", ReplyAction="http://tempuri.org/IPromotionService/UpdatePromotionResponse")]
        System.Threading.Tasks.Task UpdatePromotionAsync(System.Nullable<int> id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPromotionServiceChannel : EC.DataAccess.PromotionService.IPromotionService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PromotionServiceClient : System.ServiceModel.ClientBase<EC.DataAccess.PromotionService.IPromotionService>, EC.DataAccess.PromotionService.IPromotionService {
        
        public PromotionServiceClient() {
        }
        
        public PromotionServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PromotionServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PromotionServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PromotionServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string TestConnection() {
            return base.Channel.TestConnection();
        }
        
        public System.Threading.Tasks.Task<string> TestConnectionAsync() {
            return base.Channel.TestConnectionAsync();
        }
        
        public void CreatePromotion(EC.Entities.Entities.Promotion item) {
            base.Channel.CreatePromotion(item);
        }
        
        public System.Threading.Tasks.Task CreatePromotionAsync(EC.Entities.Entities.Promotion item) {
            return base.Channel.CreatePromotionAsync(item);
        }
        
        public EC.Entities.Entities.Promotion GetByIdPromotion(System.Nullable<int> id) {
            return base.Channel.GetByIdPromotion(id);
        }
        
        public System.Threading.Tasks.Task<EC.Entities.Entities.Promotion> GetByIdPromotionAsync(System.Nullable<int> id) {
            return base.Channel.GetByIdPromotionAsync(id);
        }
        
        public object GetAllPromotions() {
            return base.Channel.GetAllPromotions();
        }
        
        public System.Threading.Tasks.Task<object> GetAllPromotionsAsync() {
            return base.Channel.GetAllPromotionsAsync();
        }
        
        public void DeletePromotion(System.Nullable<int> id) {
            base.Channel.DeletePromotion(id);
        }
        
        public System.Threading.Tasks.Task DeletePromotionAsync(System.Nullable<int> id) {
            return base.Channel.DeletePromotionAsync(id);
        }
        
        public void UpdatePromotion(System.Nullable<int> id) {
            base.Channel.UpdatePromotion(id);
        }
        
        public System.Threading.Tasks.Task UpdatePromotionAsync(System.Nullable<int> id) {
            return base.Channel.UpdatePromotionAsync(id);
        }
    }
}
