//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EC.BusinessLogic.MyService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Promotion", Namespace="http://schemas.datacontract.org/2004/07/EC.PromotionService.Models")]
    [System.SerializableAttribute()]
    public partial class Promotion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeImageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Image {
            get {
                return this.ImageField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageField, value) != true)) {
                    this.ImageField = value;
                    this.RaisePropertyChanged("Image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TypeImage {
            get {
                return this.TypeImageField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeImageField, value) != true)) {
                    this.TypeImageField = value;
                    this.RaisePropertyChanged("TypeImage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MyService.IPromotionService")]
    public interface IPromotionService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPromotionService/GetPromotionImage", ReplyAction="http://tempuri.org/IPromotionService/GetPromotionImageResponse")]
        EC.BusinessLogic.MyService.Promotion GetPromotionImage();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPromotionService/GetPromotionImage", ReplyAction="http://tempuri.org/IPromotionService/GetPromotionImageResponse")]
        System.Threading.Tasks.Task<EC.BusinessLogic.MyService.Promotion> GetPromotionImageAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPromotionServiceChannel : EC.BusinessLogic.MyService.IPromotionService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PromotionServiceClient : System.ServiceModel.ClientBase<EC.BusinessLogic.MyService.IPromotionService>, EC.BusinessLogic.MyService.IPromotionService {
        
        public PromotionServiceClient() {
        }
        
        public PromotionServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PromotionServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PromotionServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PromotionServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public EC.BusinessLogic.MyService.Promotion GetPromotionImage() {
            return base.Channel.GetPromotionImage();
        }
        
        public System.Threading.Tasks.Task<EC.BusinessLogic.MyService.Promotion> GetPromotionImageAsync() {
            return base.Channel.GetPromotionImageAsync();
        }
    }
}
