//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EC.BusinessLogic.MyService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MyService.IPromotionService")]
    public interface IPromotionService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPromotionService/TestConnection", ReplyAction="http://tempuri.org/IPromotionService/TestConnectionResponse")]
        string TestConnection();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPromotionService/TestConnection", ReplyAction="http://tempuri.org/IPromotionService/TestConnectionResponse")]
        System.Threading.Tasks.Task<string> TestConnectionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPromotionService/CreatePromotion", ReplyAction="http://tempuri.org/IPromotionService/CreatePromotionResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Security.Policy.EvidenceBase))]
        void CreatePromotion(EC.Entities.Entities.Promotion item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPromotionService/CreatePromotion", ReplyAction="http://tempuri.org/IPromotionService/CreatePromotionResponse")]
        System.Threading.Tasks.Task CreatePromotionAsync(EC.Entities.Entities.Promotion item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPromotionService/GetByIdPromotion", ReplyAction="http://tempuri.org/IPromotionService/GetByIdPromotionResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Security.Policy.EvidenceBase))]
        EC.Entities.Entities.Promotion GetByIdPromotion(System.Nullable<int> id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPromotionService/GetByIdPromotion", ReplyAction="http://tempuri.org/IPromotionService/GetByIdPromotionResponse")]
        System.Threading.Tasks.Task<EC.Entities.Entities.Promotion> GetByIdPromotionAsync(System.Nullable<int> id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPromotionService/GetAllPromotions", ReplyAction="http://tempuri.org/IPromotionService/GetAllPromotionsResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EC.Entities.Entities.Promotion))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Security.Policy.Url))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Security.Policy.EvidenceBase))]
        object GetAllPromotions();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPromotionService/GetAllPromotions", ReplyAction="http://tempuri.org/IPromotionService/GetAllPromotionsResponse")]
        System.Threading.Tasks.Task<object> GetAllPromotionsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPromotionService/DeletePromotion", ReplyAction="http://tempuri.org/IPromotionService/DeletePromotionResponse")]
        void DeletePromotion(System.Nullable<int> id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPromotionService/DeletePromotion", ReplyAction="http://tempuri.org/IPromotionService/DeletePromotionResponse")]
        System.Threading.Tasks.Task DeletePromotionAsync(System.Nullable<int> id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPromotionService/UpdatePromotion", ReplyAction="http://tempuri.org/IPromotionService/UpdatePromotionResponse")]
        void UpdatePromotion(System.Nullable<int> id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPromotionService/UpdatePromotion", ReplyAction="http://tempuri.org/IPromotionService/UpdatePromotionResponse")]
        System.Threading.Tasks.Task UpdatePromotionAsync(System.Nullable<int> id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPromotionServiceChannel : EC.BusinessLogic.MyService.IPromotionService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PromotionServiceClient : System.ServiceModel.ClientBase<EC.BusinessLogic.MyService.IPromotionService>, EC.BusinessLogic.MyService.IPromotionService {
        
        public PromotionServiceClient() {
        }
        
        public PromotionServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PromotionServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PromotionServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PromotionServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string TestConnection() {
            return base.Channel.TestConnection();
        }
        
        public System.Threading.Tasks.Task<string> TestConnectionAsync() {
            return base.Channel.TestConnectionAsync();
        }
        
        public void CreatePromotion(EC.Entities.Entities.Promotion item) {
            base.Channel.CreatePromotion(item);
        }
        
        public System.Threading.Tasks.Task CreatePromotionAsync(EC.Entities.Entities.Promotion item) {
            return base.Channel.CreatePromotionAsync(item);
        }
        
        public EC.Entities.Entities.Promotion GetByIdPromotion(System.Nullable<int> id) {
            return base.Channel.GetByIdPromotion(id);
        }
        
        public System.Threading.Tasks.Task<EC.Entities.Entities.Promotion> GetByIdPromotionAsync(System.Nullable<int> id) {
            return base.Channel.GetByIdPromotionAsync(id);
        }
        
        public object GetAllPromotions() {
            return base.Channel.GetAllPromotions();
        }
        
        public System.Threading.Tasks.Task<object> GetAllPromotionsAsync() {
            return base.Channel.GetAllPromotionsAsync();
        }
        
        public void DeletePromotion(System.Nullable<int> id) {
            base.Channel.DeletePromotion(id);
        }
        
        public System.Threading.Tasks.Task DeletePromotionAsync(System.Nullable<int> id) {
            return base.Channel.DeletePromotionAsync(id);
        }
        
        public void UpdatePromotion(System.Nullable<int> id) {
            base.Channel.UpdatePromotion(id);
        }
        
        public System.Threading.Tasks.Task UpdatePromotionAsync(System.Nullable<int> id) {
            return base.Channel.UpdatePromotionAsync(id);
        }
    }
}
