USE ElectronicCardDB;
GO

CREATE TABLE Patients
(
    Id INT PRIMARY KEY IDENTITY,
	FirstName NVARCHAR(20) NOT NULL,
	MiddleName NVARCHAR(20) NOT NULL,
	LastName NVARCHAR(20) NOT NULL,
	DateBirth DATE NOT NULL,
	PlaceWork NVARCHAR(40) NOT NULL,
	PhotoPath NVARCHAR(50) NULL,
	UserId INT NOT NULL UNIQUE
	FOREIGN KEY REFERENCES Users(Id) ON DELETE CASCADE,
)