USE ElectronicCardDB;
GO

CREATE TABLE Records
(
    Id INT PRIMARY KEY IDENTITY,
	DateRecord DATE NOT NULL,
	UserId INT NOT NULL
	FOREIGN KEY REFERENCES Patients(Id) ON DELETE CASCADE,
	DiagnosisId INT
	FOREIGN KEY REFERENCES Diagnosis(Id) ON DELETE SET NULL,
	TherapyId INT
	FOREIGN KEY REFERENCES Therapies(Id) ON DELETE SET NULL,
	DoctorId INT
	FOREIGN KEY REFERENCES Doctors(Id) ON DELETE NO ACTION,
	SickLeaveId INT
	FOREIGN KEY REFERENCES SickLeaves(Id) ON DELETE SET NULL
)