USE ElectronicCardDB;
GO

CREATE TABLE PatientsToDoctors
(
   PatientId INT NULL
   FOREIGN KEY REFERENCES Users(Id) ON DELETE NO ACTION, 
   DoctorId INT 
   FOREIGN KEY REFERENCES Users(Id) ON DELETE CASCADE
)