USE ElectronicCardDB;
GO

CREATE TABLE Photo
(
    Id INT IDENTITY PRIMARY KEY,
    Image VARBINARY(MAX) NULL,
    ImageType NVARCHAR(50) NULL,
    UserId INT UNIQUE
    FOREIGN KEY REFERENCES dbo.Users(Id) ON DELETE CASCADE
)
GO