USE ElectronicCardDB;
GO

CREATE TABLE PatientsToDoctors
(
   PatientId INT NOT NULL
   FOREIGN KEY REFERENCES Patients(UserId) ON DELETE NO ACTION,
   DoctorId INT NOT NULL
   FOREIGN KEY REFERENCES Doctors(UserId) ON DELETE CASCADE
)