USE ElectronicCardDB;
GO

CREATE TABLE Records
(
    Id INT PRIMARY KEY IDENTITY,
	DateRecord DATE NOT NULL,
	PatientId INT NOT NULL
	FOREIGN KEY REFERENCES Patients(UserId) ON DELETE CASCADE,
	DiagnosisId INT NULL
	FOREIGN KEY REFERENCES Diagnosis(DiagnosisId) ON DELETE SET NULL,
	DoctorId INT
	FOREIGN KEY REFERENCES Doctors(UserId),
	SickLeaveId INT NULL
	FOREIGN KEY REFERENCES SickLeaves(SickLeaveId) ON DELETE SET NULL
)