USE ElectronicCardDB;
GO

CREATE TABLE Phones
(
   Id INT PRIMARY KEY IDENTITY NOT NULL,
   PhoneNumber NVARCHAR(20) UNIQUE NOT NULL,
   UserId INT NOT NULL
   FOREIGN KEY REFERENCES Users(Id) ON DELETE CASCADE
)