USE ElectronicCardDB;
GO

CREATE TABLE Users
(
     Id INT PRIMARY KEY IDENTITY,
	 Login NVARCHAR(20) UNIQUE NOT NULL,
	 Password NVARCHAR(20) NOT NULL,
	 Email NVARCHAR(30) UNIQUE NOT NULL,
	 IsDoctor BIT NOT NULL
)